# Generated by Django 5.2.17 on 2026-09-26 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Ventilator, X-Ray, Infusion Pump', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_tag', models.CharField(help_text='e.g. VEN-ICU-001', max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('manufacturer', models.CharField(db_index=True, max_length=100)),
                ('model_no', models.CharField(blank=True, max_length=100)),
                ('serial_no', models.CharField(max_length=100, unique=True)),
                ('purchase_date', models.DateField()),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('location_detail', models.CharField(blank=True, help_text='Ward / room / bed.', max_length=150)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('breakdown', 'Breakdown'), ('under_maintenance', 'Under maintenance'), ('standby', 'Standby'), ('decommissioned', 'Decommissioned')], db_index=True, default='operational', max_length=20)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=10)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('next_pm_date', models.DateField(blank=True, db_index=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipment.category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='hospital.department')),
            ],
            options={
                'ordering': ['asset_tag'],
                'indexes': [models.Index(fields=['department', 'status'], name='equipment_e_departm_5910c6_idx'), models.Index(fields=['next_pm_date', 'status'], name='equipment_e_next_pm_e725e6_idx'), models.Index(fields=['category', 'status'], name='equipment_e_categor_149399_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('warranty_expiry__isnull', True), ('warranty_expiry__gt', models.F('purchase_date')), _connector='OR'), name='equipment_warranty_after_purchase')],
            },
        ),
    ]
