# Generated by Django 5.2.17 on 2026-09-26 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('file', models.FileField(upload_to='manuals/%Y/')),
                ('file_hash', models.CharField(help_text='SHA256 for dedup.', max_length=64, unique=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_indexed', models.BooleanField(db_index=True, default=False)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manuals', to='equipment.category')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manuals', to='equipment.equipment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_manuals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('page_no', models.PositiveIntegerField(blank=True, null=True)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(help_text='~800-1000 tokens with overlap.')),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.equipmentmanual')),
            ],
            options={
                'ordering': ['manual', 'chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='equipmentmanual',
            index=models.Index(fields=['category', 'is_indexed'], name='knowledge_e_categor_a6fd2e_idx'),
        ),
        migrations.AddIndex(
            model_name='manualchunk',
            index=models.Index(fields=['manual', 'chunk_index'], name='knowledge_m_manual__28074b_idx'),
        ),
        migrations.AddConstraint(
            model_name='manualchunk',
            constraint=models.UniqueConstraint(fields=('manual', 'chunk_index'), name='uniq_chunk_manual_index'),
        ),
    ]
