# Generated by Django 5.2.17 on 2026-09-26 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('specialization', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part_no', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=5)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('compatible_categories', models.ManyToManyField(blank=True, related_name='compatible_parts', to='equipment.category')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='inventory.vendor')),
            ],
            options={
                'ordering': ['part_no'],
            },
        ),
        migrations.CreateModel(
            name='PartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost_at_use', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_usages', to='maintenance.maintenancerecord')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='inventory.sparepart')),
            ],
            options={
                'indexes': [models.Index(fields=['spare_part', 'created_at'], name='inventory_p_spare_p_6b862f_idx')],
                'constraints': [models.UniqueConstraint(fields=('maintenance_record', 'spare_part'), name='uniq_usage_record_part'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='usage_qty_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['is_active', 'quantity_in_stock'], name='inventory_s_is_acti_ef70c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='sparepart',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='part_price_non_negative'),
        ),
    ]
