# Generated by Django 5.2.17 on 2026-09-26 07:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventiveSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-yearly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='quarterly', max_length=20)),
                ('interval_days', models.PositiveIntegerField(help_text='Derived from frequency; editable for custom.')),
                ('last_done_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField(db_index=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('emergency', 'Emergency'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_assignments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_created', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_schedules', to='equipment.equipment')),
            ],
            options={
                'ordering': ['next_due_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_no', models.CharField(help_text='e.g. SR-2026-0001', max_length=20, unique=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('emergency', 'Emergency'), ('critical', 'Critical')], db_index=True, default='medium', max_length=10)),
                ('issue_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In progress'), ('on_hold', 'On hold'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened')], db_index=True, default='open', max_length=20)),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('in_progress_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('downtime_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('satisfaction_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='equipment.equipment')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective'), ('calibration', 'Calibration'), ('inspection', 'Inspection')], db_index=True, default='corrective', max_length=20)),
                ('work_done', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('downtime_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('next_action', models.TextField(blank=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/%Y/')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='equipment.equipment')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_records', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='maintenance.preventiveschedule')),
                ('service_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record', to='maintenance.servicerequest')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='preventiveschedule',
            index=models.Index(fields=['next_due_date', 'is_active'], name='maintenance_next_du_2a0a98_idx'),
        ),
        migrations.AddIndex(
            model_name='preventiveschedule',
            index=models.Index(fields=['equipment', 'is_active'], name='maintenance_equipme_304b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='preventiveschedule',
            index=models.Index(fields=['assigned_to', 'next_due_date'], name='maintenance_assigne_31068e_idx'),
        ),
        migrations.AddConstraint(
            model_name='preventiveschedule',
            constraint=models.CheckConstraint(condition=models.Q(('interval_days__gt', 0)), name='pm_interval_positive'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status', 'priority'], name='maintenance_status_538ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['assigned_to', 'status'], name='maintenance_assigne_8e0c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['equipment', 'requested_at'], name='maintenance_equipme_f67bb9_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicerequest',
            constraint=models.CheckConstraint(condition=models.Q(('satisfaction_rating__isnull', True), models.Q(('satisfaction_rating__gte', 1), ('satisfaction_rating__lte', 5)), _connector='OR'), name='sr_rating_1_to_5'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['equipment', 'completed_at'], name='maintenance_equipme_9b76ce_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['technician', 'completed_at'], name='maintenance_technic_077de1_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['maintenance_type', 'completed_at'], name='maintenance_mainten_a24114_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at__gte', models.F('started_at'))), name='record_completed_after_start'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='record_cost_non_negative'),
        ),
    ]
