# Generated by Django 5.2.17 on 2026-09-26 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_notes_equipment_vendor_equipmentstatuslog'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Reported'), ('assigned', 'Assigned'), ('status_change', 'Status change'), ('note', 'Progress note'), ('report', 'Maintenance report'), ('edited', 'Edited')], db_index=True, default='note', max_length=20)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='inspection_findings',
            field=models.TextField(blank=True, help_text='Technician inspection findings.'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='requests/%Y/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='deadline',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Manager-set target resolution.', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='internal_remarks',
            field=models.TextField(blank=True, help_text='Manager-only internal notes.'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='work_done',
            field=models.TextField(help_text='Repair actions performed.'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['deadline', 'status'], name='maintenance_deadlin_3fa2eb_idx'),
        ),
        migrations.AddField(
            model_name='serviceactivity',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sr_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceactivity',
            name='service_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='maintenance.servicerequest'),
        ),
        migrations.AddIndex(
            model_name='serviceactivity',
            index=models.Index(fields=['service_request', 'created_at'], name='maintenance_service_41e91f_idx'),
        ),
    ]
