# Generated by Django 5.2.17 on 2026-09-26 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenancerecord_checklist_results_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='maintenance.preventiveschedule'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('breakdown', 'Breakdown'), ('assignment', 'Assignment'), ('pm_due', 'PM due'), ('pm_upcoming', 'PM upcoming'), ('pm_overdue', 'PM overdue'), ('warranty', 'Warranty expiry'), ('resolved', 'Resolved'), ('system', 'System')], db_index=True, default='system', max_length=20),
        ),
    ]
